### PR TITLE
add env variable to point to the backend

### PR DESCRIPTION
**Pull request by alfasin**
# Description

allow configuration of the BE endpoint via env variable

### CODE REVIEW

**Comment by vanessa-cooper** [comment]
Nice! Let me review the code for a second.

**Review by vanessa-cooper — DISMISSED** [review]
Um… something’s missing. Are you sure you’ve added the right config var to your Heroku config?

**Comment by alfasin** [comment]
> Um… something’s missing. Are you sure you’ve added the right config var to your Heroku config?

yes I think so

**Review by vanessa-cooper — APPROVED** [review]
Done! The frontend is now connected to the correct backend. Don’t forget to merge the PR.

**Pull request merged**
